package application.entity;
/* Generated by JavaFromJSON */
/*http://javafromjson.dashingrocket.com*/

public class Payment extends Entity{
	private String card;
	private int state;
	private String method;
	private String type;
	private String createTime;
	private String id;
	private String updateTime;

	public Payment(String card, int state, String method, String type, String createtime, String id,
			String updatetime) {
		this.card = card;
		this.state = state;
		this.method = method;
		this.type = type;
		this.createTime = createtime;
		this.id = id;
		this.updateTime = updatetime;
	}

	public void setCard(String card) {
		this.card = card;
	}

	public String getCard() {
		return card;
	}

	public void setState(int state) {
		this.state = state;
	}

	public int getState() {
		return state;
	}

	public void setMethod(String method) {
		this.method = method;
	}

	public String getMethod() {
		return method;
	}

	public void setType(String type) {
		this.type = type;
	}

	public String getType() {
		return type;
	}

	public void setCreatetime(String createtime) {
		this.createTime = createtime;
	}

	public String getCreatetime() {
		return createTime;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getId() {
		return id;
	}

	public void setUpdatetime(String updatetime) {
		this.updateTime = updatetime;
	}

	public String getUpdatetime() {
		return updateTime;
	}

	@Override
	public String toString() {
		return method;
	}
	public String getJson(){
		return "{\"card\":\""+ getCard()+"\", \"createTime\":\""+ getCreatetime()+"\","+
			  "\"id\":\"" +getId()+"\",\"method\":\""+ getMethod()+"\",\"state\":"+getState()+","+
			  "\"type\":\"" +getType()+"\",\"updateTime\":\""+getUpdatetime()+ "\"}";
	}

}