package application.entity;
/* Generated by JavaFromJSON */
/*http://javafromjson.dashingrocket.com*/

public class PurchasedItemElement extends Entity{
	private int quantity;
	private Product product;
	private String type;
	private int purchasePrice;
	private int sellingPrice;
	private String unit;
	private String id;
	private String rate;
	private String status;
	private String name;
	private String description;

	public PurchasedItemElement(int quantity, Product product, String type, int purchaseprice, int sellingprice,
			String unit, String id, String rate, String status, String name, String description) {
		this.quantity = quantity;
		this.product = product;
		this.type = type;
		this.purchasePrice = purchaseprice;
		this.sellingPrice = sellingprice;
		this.unit = unit;
		this.id = id;
		this.rate = rate;
		this.status = status;
		this.name = name;
		this.description = description;
	}

	public void setQuantity(int quantity) {
		this.quantity = quantity;
	}

	public int getQuantity() {
		return quantity;
	}

	public void setProduct(Product product) {
		this.product = product;
	}

	public Product getProduct() {
		return product;
	}

	public void setType(String type) {
		this.type = type;
	}

	public String getType() {
		return type;
	}

	public void setPurchaseprice(int purchaseprice) {
		this.purchasePrice = purchaseprice;
	}

	public int getPurchaseprice() {
		return purchasePrice;
	}

	public void setSellingprice(int sellingprice) {
		this.sellingPrice = sellingprice;
	}

	public int getSellingprice() {
		return sellingPrice;
	}

	public void setUnit(String unit) {
		this.unit = unit;
	}

	public String getUnit() {
		return unit;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getId() {
		return id;
	}

	public void setRate(String rate) {
		this.rate = rate;
	}

	public String getRate() {
		return rate;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public String getStatus() {
		return status;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getName() {
		return name;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public String getDescription() {
		return description;
	}

	@Override
	public String toString() {
		return product.getCategory();
	}
	public String getJson(){
		return "{\"description\":\""+getDescription()+"\",\"id\":\""+getId()+"\","+
			  "\"name\":\""+getName()+"\",\"product\":" + getProduct().getJson() +","+
				"\"purchasePrice\": "+getPurchaseprice()+",\"quantity\": "+getQuantity()+","+
			  "\"rate\": \""+getRate()+"\",\"sellingPrice\": "+getSellingprice()+
			  ",\"status\":\""+getStatus()+"\",\"type\":\""+getType()+" \",\"unit\":\""+getUnit()+"\"}";
	}

}