package application.entity;
/* Generated by JavaFromJSON */
/*http://javafromjson.dashingrocket.com*/

public class Shipment extends Entity{
	private String shipDate;
	private String type;
	private Owner owner;
	private String id;
	private String address;

	public Shipment(String shipdate, String type, Owner owner, String id, String address) {
		this.shipDate = shipdate;
		this.type = type;
		this.owner = owner;
		this.id = id;
		this.address = address;
	}

	public void setShipdate(String shipdate) {
		this.shipDate = shipdate;
	}

	public String getShipdate() {
		return shipDate;
	}

	public void setType(String type) {
		this.type = type;
	}

	public String getType() {
		return type;
	}

	public void setOwner(Owner owner) {
		this.owner = owner;
	}

	public Owner getOwner() {
		return owner;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getId() {
		return id;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public String getAddress() {
		return address;
	}

	@Override
	public String toString() {
		return address;
	}
	public String getJson(){
		return "{\"address\":\""+getAddress()+"\",\"id\":\""+getId()+"\",\"owner\":"+getOwner().getJson()+","+
			  "\"shipDate\":\""+getShipdate()+"\",\"type\":\""+getType()+"\"}";
	}

}